langage: haskell

before_install:
 # Instructions taken from https://github.com/commercialhaskell/stack/wiki/Downloads
 - wget -q -O- http://download.fpcomplete.com/ubuntu/fpco.key | sudo apt-key add -
 - echo 'deb http://download.fpcomplete.com/ubuntu/precise stable main' | sudo tee /etc/apt/sources.list.d/fpco.list
 - sudo apt-get update
 - sudo apt-get install stack -y

install:
 - stack setup 7.10.1 --no-system-ghc
 - pip install --user cram

# Here starts the actual work to be performed for the package under test; any command which exits with a non-zero exit code causes the build to fail.
script:
 - stack test
 - $HOME/.local/bin/cram tests/functional
